config/routes.rb
SubbyDevise::Application.routes.draw do |map|
  get "public/index"

  get "public/contact"

  get "site/index"

  get "site/contact"

  
  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"

  resources :users
  resource :account

  controller :user_sessions do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  match 'register', :to => 'users#new', :as => 'register'
  match 'thanks/:id', :to => 'subscriptions#thanks', :as => 'thanks_for_registering'

  resources :products, :only => [:index] do
    resources :subscriptions, :only => [:new, :create]
  end

  constraints(Subdomain) do 
    match '/' => 'site#index'
  end

  root :to => 'public#index'

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :get_product, :only => [:new, :create]
  skip_before_filter :current_account
  
  layout 'public'
  
  def new
    @account = Account.new
    @account.users.build
  end
  
  def create
    @account = Account.new params[:account]
    if @account.create_and_subscribe(@product.id)      
      redirect_to thanks_for_registering_url(:id => @account.id)
    else
      render :action => :new
    end
  end
  
  def thanks
    @account = Account.find(params[:id])
  end
  
  private
    def get_product
      @product = Chargify::Product.find(params[:product_id])    
    end
  
  
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/new.html.erb
<h2>Signup: <%= @product.name %> Plan</h2>

<% form_for @account, :url => product_subscriptions_path(@product), :html => {:method => :post} do |form| %>

	<%= form.error_messages %>
	<h2>About your business</h2>
	<fieldset>
		<p><%= form.label :name, 'Business name' %><br />
		<%= form.text_field :name %></p>		
		
		<p><%= form.label :first_name %><br />
		<%= form.text_field :first_name %>	</p>	

		<p><%= form.label :last_name %><br />
		<%= form.text_field :last_name %></p>
		
		<p><%= form.label :email %><br />
		<%= form.text_field :email %></p>
	
		<p><%= form.label :domain, 'Domain of your site' %><br />
		<%= form.text_field :domain %></p>		

		<p><%= form.label :subdomain, 'Choose a temporary subdomain' %><br />
		<%= form.text_field :subdomain %>.mydomain.com</p>
	</fieldset>
	
	<h2>Create a login</h2>
  <fieldset>
    <% form.fields_for(:users) do |u| %>
      <p><%= u.label :username, 'Choose a login' %><br /> <%= u.text_field :username %></p>
      
      <p><%= u.label :email %><br /> <%= u.text_field :email %></p>
      
      <p><label for="user_password">Password</label><br />
      <%= u.password_field :password %></p>
      
      <p><label for="user_password_confirmation">Password Confirmation</label><br />
      <%= u.password_field :password_confirmation %></p>
    <% end %>
  </fieldset>
	
	<h2>Enter your billing information</h2>
	<fieldset>
		<p><%= form.label :credit_card_number, "Credit Card Number" %><br />
		<%= form.text_field :credit_card_number %></p>

		<p><%= form.label :cvv %><br />
		<%= form.text_field :cvv %></p>

		<p><%= form.label :expiration_month %><br />
		<%= form.text_field :expiration_month %></p>

		<p><%= form.label :expiration_year %><br />
		<%= form.text_field :expiration_year %></p>
	</fieldset>
	
	<p><%= form.submit "Submit" %></p>
	
	
	
<% end %>

app/views/subscriptions/thanks.html.erb
<h2>Thanks for Registering!</h2>

Now go to <%= @account.subdomain %>.getcilantro.com to sign-in and get started ... 