config/routes.rb
SubbyDevise::Application.routes.draw do |map|
  get "public/index"

  get "public/contact"

  get "site/index"

  get "site/contact"

  
  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"

  resources :users
  resource :account

  controller :user_sessions do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  match 'register', :to => 'users#new', :as => 'register'
  match 'thanks/:id', :to => 'subscriptions#thanks', :as => 'thanks_for_registering'

  resources :products, :only => [:index] do
    resources :subscriptions, :only => [:new, :create]
  end

  constraints(Subdomain) do 
    match '/' => 'site#index'
  end

  root :to => 'public#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>SubbyDevise</title>
<%= stylesheet_link_tag 'reset', 'text', '960', 'application' %>
<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js" %>
<%= javascript_include_tag 'rails' %>
<%= csrf_meta_tag %>
</head>
<body>
  <header>
    <% if current_user %>
      welcome <%= current_user.username %> <%= link_to 'logout', logout_url, :method => :delete %>
    <% else %>
      <%= link_to 'login', login_url %>
    <% end %>
  </header>
  
  <section>
    <aside id="sidebar">
      <h2>Users</h2>
      <p>...</p>
      <h2>Foos</h2>
      <p>...</p>
      <h2>Bars</h2>
      <p>...</p>
    </aside>
    <article>
      <%= yield %>
    </article>
  </section>
</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SubbyDevise</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js" %>
  <%= javascript_include_tag 'rails' %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
<title>SubbyDevise</title>
<%= stylesheet_link_tag 'reset', 'text', '960', 'session' %>
<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js" %>
<%= javascript_include_tag 'rails' %>
<%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>