config/routes.rb
SubbyDevise::Application.routes.draw do |map|
  get "public/index"

  get "public/contact"

  get "site/index"

  get "site/contact"

  
  get "user_sessions/new"
  get "user_sessions/create"
  get "user_sessions/destroy"

  resources :users
  resource :account

  controller :user_sessions do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  match 'register', :to => 'users#new', :as => 'register'
  match 'thanks/:id', :to => 'subscriptions#thanks', :as => 'thanks_for_registering'

  resources :products, :only => [:index] do
    resources :subscriptions, :only => [:new, :create]
  end

  constraints(Subdomain) do 
    match '/' => 'site#index'
  end

  root :to => 'public#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  
  has_many :users, :dependent => :destroy
  
  accepts_nested_attributes_for :users
  authenticates_many :user_sessions, :find_options => { :limit => 1 } 
  
  validates_presence_of [:expiration_month, :expiration_year, :credit_card_number, :cvv], :on => :create
  
  attr_accessor :expiration_month, :expiration_year, 
                :credit_card_number, :cvv, :user
  
  before_destroy :cancel_subscription
                
  def create_and_subscribe(product_id)
    return unless self.valid?
    Account.transaction do
      self.save
      subscription = Chargify::Subscription.new(subscription_params(product_id))
      if subscription.save
        self.update_attributes!(:customer_id => subscription.customer.id, :subscription_id => subscription.id)
      else
        subscription.errors.full_messages.each{|err| errors.add_to_base(err)}
        false
        raise ActiveRecord::Rollback 
      end
    end
  end                

  def subscription
    Chargify::Subscription.find(subscription_id)
  end
  
  def customer
    Chargify::Customer.find(customer_id)
  end         
  
  private
  
    def cancel_subscription
      Chargify::Subscription.delete(subscription_id)
    end
  
    def customer_params
      {
        :first_name   => first_name,
        :last_name    => last_name,
        :email        => email,
        :reference    => id,
        :organization => "",      
      }
    end
  
    def subscription_params(product_id)
      {
        :product_id => product_id,
        :customer_attributes => customer_params,
        :credit_card_attributes => {
          :full_number => credit_card_number,        
          :cvv => cvv,
          :expiration_month => expiration_month,
          :expiration_year => expiration_year
        }      
      }
    end
       
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def show
    @account = @current_account
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @account }
    end
  end

  def new
    @account = Account.new
    @products = Chargify::Product.find(:all) 
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @account }
    end
  end

  def edit
    @account = @current_account
  end

  def create
    @account = @current_account
    respond_to do |format|
      if @account.save
        format.html { redirect_to(@account, :notice => 'Account was successfully created.') }
        format.xml  { render :xml => @account, :status => :created, :location => @account }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @account = @current_account
    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to(@account, :notice => 'Account was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @account = @current_account
    @account.destroy
    respond_to do |format|
      format.html { redirect_to(accounts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New account</h1>

<h2>Current Producs</h2>
<% @products.each do |product| %>
	<h2><%= product.name %></h2>
	<p><%= product.description %></p>	
<% end %>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<h2>Your Account Info</h2>

<p><%= @account.name %></p>

<p><%= @account.email %></p>

<%= link_to 'Edit', edit_account_path %>